name: Deploy MAIN WSL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Desplegar en producción (main)
    runs-on: [self-hosted, linux, x64, wsl]

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Mostrar mensaje
        run: echo "Desplegando rama MAIN..."

      - name: Crear carpeta destino
        run: mkdir -p /var/www/html/laboratorio-wsl

      - name: Copiar archivos (sin borrar existentes)
        run: rsync -av index.html css .github /var/www/html/laboratorio-wsl/

      - name: Verificar despliegue
        run: ls -la /var/www/html/laboratorio-wsl/