name: Deploy to Nginx Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Nginx Server
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Mostrar mensaje
        run: echo "Desplegando rama main en WSL..."

      - name: Crear carpeta destino
        run: sudo mkdir -p /var/www/html/Plataforma_web_AR_3D/

      - name: Copiar archivos
        run: |
          sudo rsync -av --delete --no-group --no-perms \
          --exclude='.git' \
          --exclude='.github' \
          ./ /var/www/html/Plataforma_web_AR_3D/

      - name: Recargar Nginx
        run: sudo systemctl reload nginx

      - name: Verificar despliegue
        run: ls -la /var/www/html/Plataforma_web_AR_3D/